# Generated by Django 4.2.5 on 2023-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_test', '0003_rename_user_id_tguser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
